use_frameworks!

platform :ios, '10.0'

target 'SRPermenantThread_Example' do
  pod 'SRPermenantThread', :path => '../'

  target 'SRPermenantThread_Tests' do
    inherit! :search_paths

    
  end
end
